/*Eason,Gordon,Brycen
  June 9 2020 
  This the main menu for the user 
 */
package Game;

import java.io.File;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;


/**
 *
 * @author Eason
 */
public class MainMenu extends javax.swing.JFrame {
    //calls a new object from the class panel  
    public static Draw draw = new Draw();

    public MainMenu() {
        initComponents();
        //sets the screen in the middle 
        setLocationRelativeTo(null);
    }

    public static void scoreSort(ArrayList<Integer> num) {

        for (int i = 0; i < num.size(); i++) {
            // find position of smallest num between (i + 1)th element and last element
            int pos = i;
            for (int j = i; j < num.size(); j++) {
                if (num.get(j) > num.get(pos)) {
                    pos = j;
                }
            }
            // Swap min (smallest num) to current position on array
            int min = num.get(pos);
            num.set(pos, num.get(i));
            num.set(i, min);

        }
    }

    public int search(ArrayList<Integer> elements, int target) {
        return elements.indexOf(target);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnScore = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Phosphate", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SPACE INVADERS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 20, 290, 60);

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlay);
        btnPlay.setBounds(10, 100, 280, 29);

        jButton2.setText("How to Play");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 150, 280, 29);

        jButton3.setText("Credits");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 200, 280, 29);

        btnScore.setText("High Score");
        btnScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoreActionPerformed(evt);
            }
        });
        jPanel1.add(btnScore);
        btnScore.setBounds(10, 250, 280, 29);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 290, 280, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SpaceBackground.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 300, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 298, 383);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Welcome To Space Invaders\nTo Play this Game:\n -Use the left and right arrow keys to move"
                + "\n- Press or hold the spacebar to shoot\nWhen In Game Press e to exit the game\nMax Level is 6 \nIf the Aliens passed the barrier you will lost a life"
                + "\nIf you life Goes Down to zero you Lose\nPress e to exit the game and esc to show the main Menu");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
       //calls a new gameboard 
        GameBoard gb = new GameBoard();
        //open the gameboard
        gb.setVisible(true);
        //closes the mainmenu 
        MainMenu mr = new MainMenu();
        mr.setVisible(false);
    }//GEN-LAST:event_btnPlayActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //credits
        JOptionPane.showMessageDialog(null, "Credits:Eason,Gordon,Brycen :D");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoreActionPerformed
        //try and catch to read the data file 
        try {
            //array lists for the score object 
            ArrayList<Score> scoreList = new ArrayList();
            //array list for the sorted numbers
            ArrayList<Integer> sortNum = new ArrayList();
            //array lists from the number in the text file 
            ArrayList<Integer> num = new ArrayList();
            Score score;
            //file path ways
           InputStream in = MainMenu.class.getResourceAsStream("Score.txt");
            //use scanner to read the file 
            Scanner sr = new Scanner(in);
            //while there is a next line 
            while (sr.hasNextLine()) {
                //new score object is created 
                score = new Score();
                //the values to that score object are set 
                score.setName(sr.nextLine());
                score.setScore(Integer.parseInt(sr.nextLine()));
                //add this object to the array list 
                scoreList.add(score);
                //this is the regular array list
                num.add(score.getScore());
                //this array list will be sorted into decending order 
                sortNum.add(score.getScore());

            }
            //sort the number to highest to lowest 
            scoreSort(sortNum);
           //use an array to add data to the top 5 scores 
            String messages[] = new String[5];
            //for loop use with array to initlize the arrays
            for (int i = 0; i < messages.length; i++) {
                messages[i] = "";
            }
            //counter uses to show what place the player is 
            int counter = 0;
   
            //for loop goes through array 
            for (int i = 0; i < 5; i++) {
                //counter moves up 
                counter++;
                //add the message to the array 
                    if(i!=5){
                           messages[i] = counter + "." + scoreList.get(search(num, sortNum.get(i))) + "\n";
                    }
                  
                
               

            }
            //Show the top 5 scores 
            JOptionPane.showMessageDialog(null, messages[0] + "\n" + messages[1] + "\n" + messages[2] + "\n" + messages[3] + "\n" + messages[4] + "\n");

           
        } catch (Exception e) {
            System.out.println("Error" + e);
        }
    }//GEN-LAST:event_btnScoreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Exits the program
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnScore;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
